apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exam-service
  template:
    metadata:
      labels:
        app: exam-service
    spec:
      containers:
        - name: exam-service
          image: JQKStudy/exam-service
          ports:
            - containerPort: 9002
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: exam-service
spec:
  selector:
    app: exam-service
  ports:
    - port: 9002
      protocol: TCP
      name: grpc
      targetPort: 9002
  type: ClusterIP
